package seedfinder;

public class Blocks {

	private Blocks() {
	}

	// @formatter:off
	public static final int
			AIR = 0,
			STONE = 1,
			GRASS = 2,
			DIRT = 3,
			COBBLESTONE = 4,
			PLANKS = 5,
			BEDROCK = 7,
			FLOWING_WATER = 8,
			WATER = 9,
			FLOWING_LAVA = 10,
			LAVA = 11,
			SAND = 12,
			GRAVEL = 13,
			LOG = 17,
			LEAVES = 18,
			SANDSTONE = 24,
			WOOL = 35,
			DOUBLE_STONE_SLAB = 43,
			STONE_SLAB = 44,
			BOOKSHELF = 47,
			TORCH = 50,
			MOB_SPAWNER = 52,
			OAK_STAIRS = 53,
			CHEST = 54,
			CRAFTING_TABLE = 58,
			WHEAT = 59,
			FARMLAND = 60,
			FURNACE = 61,
			OAK_DOOR = 64,
			LADDER = 65,
			STONE_STAIRS = 67,
			IRON_DOOR = 71,
			WOODEN_PRESSURE_PLATE = 72,
			STONE_BUTTON = 77,
			SNOW_LAYER = 78,
			ICE = 79,
			SNOW = 80,
			OAK_FENCE = 85,
			STONEBRICK = 98,
			IRON_BARS = 101,
			GLASS_PANE = 102,
			STONE_BRICK_STAIRS = 109,
			MYCELIUM = 110,
			WATERLILY = 111,
			END_PORTAL = 119,
			END_PORTAL_FRAME = 120,
			SANDSTONE_STAIRS = 128,
			SPRUCE_STAIRS = 134,
			CARROTS = 141,
			POTATOES = 142,
			LEAVES2 = 161,
			LOG2 = 162,
			ACACIA_STAIRS = 163,
			HARDENED_CLAY = 172,
			RED_SANDSTONE = 179,
			SPRUCE_FENCE = 188,
			ACACIA_FENCE = 192,
			SPRUCE_DOOR = 193,
			ACACIA_DOOR = 196,
			BEETROOTS = 207,
			GRASS_PATH = 208;
	// @formatter:on

	private static final boolean[] BLOCKS_MOVEMENT = new boolean[256];
	static {
		BLOCKS_MOVEMENT[AIR] = false;
		BLOCKS_MOVEMENT[STONE] = true;
		BLOCKS_MOVEMENT[GRASS] = true;
		BLOCKS_MOVEMENT[DIRT] = true;
		BLOCKS_MOVEMENT[COBBLESTONE] = true;
		BLOCKS_MOVEMENT[PLANKS] = true;
		BLOCKS_MOVEMENT[BEDROCK] = true;
		BLOCKS_MOVEMENT[FLOWING_WATER] = false;
		BLOCKS_MOVEMENT[WATER] = false;
		BLOCKS_MOVEMENT[FLOWING_LAVA] = false;
		BLOCKS_MOVEMENT[LAVA] = false;
		BLOCKS_MOVEMENT[SAND] = true;
		BLOCKS_MOVEMENT[GRAVEL] = true;
		BLOCKS_MOVEMENT[LOG] = true;
		BLOCKS_MOVEMENT[LEAVES] = true;
		BLOCKS_MOVEMENT[SANDSTONE] = true;
		BLOCKS_MOVEMENT[WOOL] = true;
		BLOCKS_MOVEMENT[DOUBLE_STONE_SLAB] = true;
		BLOCKS_MOVEMENT[STONE_SLAB] = true;
		BLOCKS_MOVEMENT[BOOKSHELF] = true;
		BLOCKS_MOVEMENT[TORCH] = false;
		BLOCKS_MOVEMENT[MOB_SPAWNER] = true;
		BLOCKS_MOVEMENT[OAK_STAIRS] = true;
		BLOCKS_MOVEMENT[CHEST] = true;
		BLOCKS_MOVEMENT[CRAFTING_TABLE] = true;
		BLOCKS_MOVEMENT[WHEAT] = false;
		BLOCKS_MOVEMENT[FARMLAND] = true;
		BLOCKS_MOVEMENT[FURNACE] = true;
		BLOCKS_MOVEMENT[OAK_DOOR] = true;
		BLOCKS_MOVEMENT[LADDER] = false;
		BLOCKS_MOVEMENT[STONE_STAIRS] = true;
		BLOCKS_MOVEMENT[IRON_DOOR] = true;
		BLOCKS_MOVEMENT[WOODEN_PRESSURE_PLATE] = false;
		BLOCKS_MOVEMENT[STONE_BUTTON] = false;
		BLOCKS_MOVEMENT[SNOW_LAYER] = false;
		BLOCKS_MOVEMENT[ICE] = true;
		BLOCKS_MOVEMENT[SNOW] = true;
		BLOCKS_MOVEMENT[OAK_FENCE] = true;
		BLOCKS_MOVEMENT[STONEBRICK] = true;
		BLOCKS_MOVEMENT[IRON_BARS] = true;
		BLOCKS_MOVEMENT[GLASS_PANE] = true;
		BLOCKS_MOVEMENT[STONE_BRICK_STAIRS] = true;
		BLOCKS_MOVEMENT[MYCELIUM] = true;
		BLOCKS_MOVEMENT[WATERLILY] = false;
		BLOCKS_MOVEMENT[END_PORTAL] = false;
		BLOCKS_MOVEMENT[END_PORTAL_FRAME] = true;
		BLOCKS_MOVEMENT[SANDSTONE_STAIRS] = true;
		BLOCKS_MOVEMENT[IRON_DOOR] = true;
		BLOCKS_MOVEMENT[SPRUCE_STAIRS] = true;
		BLOCKS_MOVEMENT[CARROTS] = false;
		BLOCKS_MOVEMENT[POTATOES] = false;
		BLOCKS_MOVEMENT[LEAVES2] = true;
		BLOCKS_MOVEMENT[LOG2] = true;
		BLOCKS_MOVEMENT[ACACIA_STAIRS] = true;
		BLOCKS_MOVEMENT[HARDENED_CLAY] = true;
		BLOCKS_MOVEMENT[RED_SANDSTONE] = true;
		BLOCKS_MOVEMENT[SPRUCE_FENCE] = true;
		BLOCKS_MOVEMENT[ACACIA_FENCE] = true;
		BLOCKS_MOVEMENT[SPRUCE_DOOR] = true;
		BLOCKS_MOVEMENT[ACACIA_DOOR] = true;
		BLOCKS_MOVEMENT[BEETROOTS] = false;
		BLOCKS_MOVEMENT[GRASS_PATH] = true;
	}

	public static boolean isAir(int block) {
		return block == AIR;
	}

	public static boolean isLiquid(int block) {
		return block == WATER || block == LAVA || block == FLOWING_WATER || block == FLOWING_LAVA;
	}

	public static boolean blocksMovement(int block) {
		if (block < 0 || block >= 256) {
			return false;
		} else {
			return BLOCKS_MOVEMENT[block];
		}
	}

}
