package seedfinder.loot;

import static seedfinder.loot.ILootFunction.*;

import seedfinder.Items;

public class LootTables {

	// @formatter:off
	public static final LootTable STRONGHOLD_CORRIDOR =
		LootTable.Builder.create()
			.startPool()
				.setRolls(2, 3)
				.startItemEntry(Items.ENDER_PEARL)
					.setWeight(10)
				.endEntry()
				.startItemEntry(Items.DIAMOND)
					.addFunction(setCount(1, 3))
					.setWeight(3)
				.endEntry()
				.startItemEntry(Items.IRON_INGOT)
					.addFunction(setCount(1, 5))
					.setWeight(10)
				.endEntry()
				.startItemEntry(Items.GOLD_INGOT)
					.addFunction(setCount(1, 3))
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.REDSTONE)
					.addFunction(setCount(4, 9))
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.BREAD)
					.addFunction(setCount(1, 3))
					.setWeight(15)
				.endEntry()
				.startItemEntry(Items.APPLE)
					.addFunction(setCount(1, 3))
					.setWeight(15)
				.endEntry()
				.startItemEntry(Items.IRON_PICKAXE)
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.IRON_SWORD)
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.IRON_CHESTPLATE)
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.IRON_HELMET)
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.IRON_LEGGINGS)
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.IRON_BOOTS)
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.GOLDEN_APPLE)
					.setWeight(1)
				.endEntry()
				.startItemEntry(Items.SADDLE)
					.setWeight(1)
				.endEntry()
				.startItemEntry(Items.IRON_HORSE_ARMOR)
					.setWeight(1)
				.endEntry()
				.startItemEntry(Items.GOLDEN_HORSE_ARMOR)
					.setWeight(1)
				.endEntry()
				.startItemEntry(Items.DIAMOND_HORSE_ARMOR)
					.setWeight(1)
				.endEntry()
				.startItemEntry(Items.BOOK)
					.setWeight(1)
					.addFunction(enchantWithLevels(30, true))
				.endEntry()
			.endPool()
		.build();
	
	public static final LootTable STRONGHOLD_CROSSING =
		LootTable.Builder.create()
			.startPool()
				.setRolls(1, 4)
				.startItemEntry(Items.IRON_INGOT)
					.addFunction(setCount(1, 5))
					.setWeight(10)
				.endEntry()
				.startItemEntry(Items.GOLD_INGOT)
					.addFunction(setCount(1, 3))
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.REDSTONE)
					.addFunction(setCount(4, 9))
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.COAL)
					.addFunction(setCount(3, 8))
					.setWeight(10)
				.endEntry()
				.startItemEntry(Items.BREAD)
					.addFunction(setCount(1, 3))
					.setWeight(15)
				.endEntry()
				.startItemEntry(Items.APPLE)
					.addFunction(setCount(1, 3))
					.setWeight(15)
				.endEntry()
				.startItemEntry(Items.IRON_PICKAXE)
					.setWeight(1)
				.endEntry()
				.startItemEntry(Items.BOOK)
					.setWeight(1)
					.addFunction(enchantWithLevels(30, true))
				.endEntry()
			.endPool()
		.build();
	
	public static final LootTable STRONGHOLD_LIBRARY =
		LootTable.Builder.create()
			.startPool()
				.setRolls(2, 10)
				.startItemEntry(Items.BOOK)
					.addFunction(setCount(1, 3))
					.setWeight(20)
				.endEntry()
				.startItemEntry(Items.PAPER)
					.addFunction(setCount(2, 7))
					.setWeight(20)
				.endEntry()
				.startItemEntry(Items.MAP)
					.setWeight(1)
				.endEntry()
				.startItemEntry(Items.COMPASS)
					.setWeight(1)
				.endEntry()
				.startItemEntry(Items.BOOK)
					.setWeight(10)
					.addFunction(enchantWithLevels(30, true))
				.endEntry()
			.endPool()
		.build();
	
	public static final LootTable VILLAGE_BLACKSMITH =
		LootTable.Builder.create()
			.startPool()
				.setRolls(3, 8)
				.startItemEntry(Items.DIAMOND)
					.addFunction(setCount(1, 3))
					.setWeight(3)
				.endEntry()
				.startItemEntry(Items.IRON_INGOT)
					.addFunction(setCount(1, 5))
					.setWeight(10)
				.endEntry()
				.startItemEntry(Items.GOLD_INGOT)
					.addFunction(setCount(1, 3))
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.BREAD)
					.addFunction(setCount(1, 3))
					.setWeight(15)
				.endEntry()
				.startItemEntry(Items.APPLE)
					.addFunction(setCount(1, 3))
					.setWeight(15)
				.endEntry()
				.startItemEntry(Items.IRON_PICKAXE)
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.IRON_SWORD)
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.IRON_CHESTPLATE)
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.IRON_HELMET)
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.IRON_LEGGINGS)
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.IRON_BOOTS)
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.OBSIDIAN)
					.addFunction(setCount(3, 7))
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.SAPLING)
					.addFunction(setCount(3, 7))
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.SADDLE)
					.setWeight(3)
				.endEntry()
				.startItemEntry(Items.IRON_HORSE_ARMOR)
					.setWeight(1)
				.endEntry()
				.startItemEntry(Items.GOLDEN_HORSE_ARMOR)
					.setWeight(1)
				.endEntry()
				.startItemEntry(Items.DIAMOND_HORSE_ARMOR)
					.setWeight(1)
				.endEntry()
			.endPool()
		.build();
	
	public static final LootTable ABANDONED_MINESHAFT =
		LootTable.Builder.create()
			.startPool()
				.setRolls(1)
				.startItemEntry(Items.GOLDEN_APPLE)
					.setWeight(20)
				.endEntry()
				.startItemEntry(Items.GOLDEN_APPLE)
					.setWeight(1)
					.addFunction(setDamage(1))
				.endEntry()
				.startItemEntry(Items.NAME_TAG)
					.setWeight(30)
				.endEntry()
				.startItemEntry(Items.BOOK)
					.setWeight(10)
					.addFunction(enchantRandomly())
				.endEntry()
				.startItemEntry(Items.IRON_PICKAXE)
					.setWeight(5)
				.endEntry()
				.startEmptyEntry()
					.setWeight(5)
				.endEntry()
			.endPool()
			.startPool()
				.setRolls(2, 4)
				.startItemEntry(Items.IRON_INGOT)
					.addFunction(setCount(1, 5))
					.setWeight(10)
				.endEntry()
				.startItemEntry(Items.GOLD_INGOT)
					.addFunction(setCount(1, 3))
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.REDSTONE)
					.addFunction(setCount(4, 9))
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.DYE)
					.addFunction(setDamage(4))
					.addFunction(setCount(4, 9))
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.DIAMOND)
					.addFunction(setCount(1, 2))
					.setWeight(3)
				.endEntry()
				.startItemEntry(Items.COAL)
					.addFunction(setCount(3, 8))
					.setWeight(10)
				.endEntry()
				.startItemEntry(Items.BREAD)
					.addFunction(setCount(1, 3))
					.setWeight(15)
				.endEntry()
				.startItemEntry(Items.MELON_SEEDS)
					.addFunction(setCount(2, 4))
					.setWeight(10)
				.endEntry()
				.startItemEntry(Items.PUMPKIN_SEEDS)
					.addFunction(setCount(2, 4))
					.setWeight(10)
				.endEntry()
				.startItemEntry(Items.BEETROOT_SEEDS)
					.addFunction(setCount(2, 4))
					.setWeight(10)
				.endEntry()
			.endPool()
			.startPool()
				.setRolls(3)
				.startItemEntry(Items.RAIL)
					.addFunction(setCount(4, 8))
					.setWeight(20)
				.endEntry()
				.startItemEntry(Items.GOLDEN_RAIL)
					.addFunction(setCount(1, 4))
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.DETECTOR_RAIL)
					.addFunction(setCount(1, 4))
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.ACTIVATOR_RAIL)
					.addFunction(setCount(1, 4))
					.setWeight(5)
				.endEntry()
				.startItemEntry(Items.TORCH)
					.addFunction(setCount(1, 16))
					.setWeight(15)
				.endEntry()
			.endPool()
		.build();
	// @formatter:on

}
